### ISSUE TITLE
change source links

### ISSUE THREAD

**Issue by himanshu007-creator** [himanshu007-creator/weather-app#1]
In files  <code>index.html , css,js</code>, modify links so as github pages work properly, at present, they don't work.

**Comment by d4rkener** [comment]
wait lemme try

**Comment by d4rkener** [comment]
hey can you please describe more about the bug??

**Comment by himanshu007-creator** [comment]
yes , sure! when we download and run this project in local machine, it runs fine, but when i try to deploy to github pages, url's dont work, I am referring to this:-

https://github.com/himanshu007-creator/weather-app/blob/3aad5d6f6a8ddafa8f2fab8f6886142d18190ac0/index.html#L29

https://github.com/himanshu007-creator/weather-app/blob/3aad5d6f6a8ddafa8f2fab8f6886142d18190ac0/src/script.js#L21

https://github.com/himanshu007-creator/weather-app/blob/3aad5d6f6a8ddafa8f2fab8f6886142d18190ac0/src/script.js#L24
